export const GH_RAW = 'https://raw.githubusercontent.com/julesr0y/f1-circuits-svg/7c870f13587abd20aa95fd2701a3840283c70a8f/circuits/black-outline/';

export const CIRCUIT_MAP: Record<string, string> = {
  'bahrain':      'bahrain-1',  'sakhir':       'bahrain-1',  'jeddah':       'jeddah-1',
  'saudi':        'jeddah-1',   'albert park':  'melbourne-2','melbourne':    'melbourne-2',
  'australia':    'melbourne-2','suzuka':       'suzuka-2',   'japan':        'suzuka-2',
  'shanghai':     'shanghai-1', 'china':        'shanghai-1', 'miami':        'miami-1',
  'imola':        'imola-3',    'monaco':       'monaco-5',   'montreal':     'montreal-6',
  'canada':       'montreal-6', 'gilles villeneuve': 'montreal-6','barcelona':    'catalunya-6',
  'catalunya':    'catalunya-6','spain':        'catalunya-6','spielberg':    'spielberg-3',
  'red bull ring':'spielberg-3','austria':      'spielberg-3','silverstone':  'silverstone-8',
  'britain':      'silverstone-8','uk':           'silverstone-8','great britain':'silverstone-8',
  'hungaroring':  'hungaroring-3','budapest':     'hungaroring-3','hungary':      'hungaroring-3',
  'spa':          'spa-francorchamps-4','francorchamps':'spa-francorchamps-4','belgium':      'spa-francorchamps-4',
  'zandvoort':    'zandvoort-5','netherlands':  'zandvoort-5','holland':      'zandvoort-5',
  'monza':        'monza-6',    'italy':        'monza-6',    'baku':         'baku-1',
  'azerbaijan':   'baku-1',     'marina bay':   'marina-bay-4','singapore':    'marina-bay-4',
  'austin':       'austin-1',   'cota':         'austin-1',   'americas':     'austin-1',
  'mexico city':  'mexico-city-3','mexico':       'mexico-city-3','hermanos':     'mexico-city-3',
  'interlagos':   'interlagos-2','sao paulo':    'interlagos-2','brazil':       'interlagos-2',
  'las vegas':    'las-vegas-1','vegas':        'las-vegas-1','lusail':       'lusail-1',
  'qatar':        'lusail-1',   'yas marina':   'yas-marina-2','abu dhabi':    'yas-marina-2',
  'abudhabi':     'yas-marina-2',
  'istanbul':     'istanbul-1', 'turkey':       'istanbul-1', 'portimao':     'portimao-1',
  'portugal':     'portimao-1', 'mugello':      'mugello-1',  'nurburgring':  'nurburgring-4',
  'nürburgring':  'nurburgring-4','sochi':        'sochi-1',  'russia':       'sochi-1',
  'sepang':       'sepang-1',   'malaysia':     'sepang-1',   'yeongam':      'yeongam-1',
  'korea':        'yeongam-1',  'buddh':        'buddh-1',    'india':        'buddh-1',
  'aida':         'aida-1',     'magny-cours':  'magny-cours-3','magny cours':  'magny-cours-3',
  'france':       'magny-cours-3','paul ricard':  'paul-ricard-3','hockenheim':   'hockenheimring-4',
  'germany':      'hockenheimring-4','estoril':      'estoril-2','valencia':     'valencia-1',
  'jerez':        'jerez-2',
};
